---
title: "Lab 5-B"
author: "Angelina Venetto"
date: "2/27/2022"
output: html_document
---

```{r}
library(tidyverse)
set.seed(123)
missing_w2_parent <- sample(1:500, 30)
missing_w2_child <- c(missing_w2_parent[1:5], sample(1:500, 25))
family  <- read_csv(
  "https://raw.githubusercontent.com/bwiernik/progdata/main/inst/tutorials/data/family_data.csv"
) |> 
  mutate(
    across(
      starts_with("w2") & contains("parent"),
      ~ ifelse(family_id %in% missing_w2_parent, NA_real_, .x)
    ),
    across(
      starts_with("w2") & contains("child"),
      ~ ifelse(family_id %in% missing_w2_child, NA_real_, .x)
    )
  )
```
```{r}
family_longest <- family |> 
  pivot_longer(
    cols = w1_comm_parent:w2_satis_child,
    names_to = c("family_id", "family_member", "wave", "scale"),
    names_perfix = "w1" "w2",
    names_sep = "_",
    values_to = "score"
    
  )

print(family_longest)
```

```{r}
WHO <- who |>
    select(country:year, starts_with("new_")) |> 
    rename_with(~ stringr::str_replace(.x, "f", "f_"), starts_with("new_")) |> 
    rename_with(~ stringr::str_replace(.x, "m", "m_"), starts_with("new_"))
knitr::kable(WHO, rownames = FALSE)
```