---
title: "lab3-02082022"
author: "Angelina Venetto"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup}
library(dplyr)
library(tidyverse)
library(gapminder)
palmerpenguins::penguins
library(palmerpenguins)
glimpse(gapminder)
select(gapminder,country, year)
```
#Exercise  1.1/1.2
```{r}


gapminder_clean <- gapminder |>
  filter((country == "Afghanistan" | country == "Albania" | country == "Algeria") & year >= 1970, year < 1980) |>
  select(country, gdpPercap)

print(gapminder_clean)

```
```{r}
print(gapminder)
```
#Exercise 1.3
```{r}
LifeExp_drop <- gapminder |>
  group_by(country) |>
  mutate(lifeExp_drop = lifeExp - lag(lifeExp)) |>
  filter(lifeExp_drop < "0")
  print(LifeExp_drop)
```
#Exercise 1.4
```{r}
MaxGDP <- gapminder |>
```

#Exercise 1.5 
```{r}
Canada <- gapminder |>
  filter(country == "Canada")
```
```{r}
ggplot(Canada) +
  aes(x = gdpPercap, y = lifeExp) +
  geom_point()
scale_x_continuous(
 
  trans = "log10"
)
```

#Exercise 2.1
```{r}
gapminder |>
  summarize(
    mean = mean(lifeExp),
    sd = sd(lifeExp),
    median = median(lifeExp)
  )
```
```{r}
 gapminder |>
  summarize(
    mean = mean(gdpPercap),
    sd = sd(gdpPercap),
    median = median(gdpPercap)
  )
```
    
```{r}
ggplot(gapminder) +
  aes(x = gdpPercap, y = lifeExp) +
  geom_point() +
geom_smooth()

```

#Exercise 2.2
```{r}
penguins |>
  summarize(
    mean = mean(bill_length_mm),
    sd = sd(bill_length_mm),
    median = median(bill_length_mm),
    n = n(species)
  )
```
```{r}
ggplot(penguins) +
  aes(y = species,
      x = bill_length_mm,
      fill = species,
      color = species) +
  geom_boxplot(color = "black",
               alpha = .4,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position_nudge(y = .2))
```
#referenced the raincloud plot from 16.9 on our lab website




