---
title: "Lab 02 - Plastic waste"
author: "Insert your name here"
date: "Insert date here"
output: html_document
---

## Load packages and data
```{r}
library(tidyverse)
library(ggplot2)
library(here)
```

```{r}
plastic_waste <- read_csv(here::here("data", "plastic-waste.csv"))
```

## Exercises

### Exercise 1

NA = missing values 

```{r plastic-waste-continent}
#ggplot(data = plastic_waste) +
  #aes(x = plastic_waste_per_cap) +
   #geom_histogram(aes(y = after_stat(count)
```

```{r}
#ggplot(plastic_waste) +
  #aes(x = continent, y = plastic_waste_per_cap, fill = "pink") +
  #geom_density(aes(y = after_stat(count), color = continent, alpha = .1)

```

### Exercise 2

```{r plastic-waste-density}
ggplot(na.omit(plastic_waste)) +
  aes(y = plastic_waste_per_cap,
      x = continent,
      fill = continent,
      color = continent) +
  geom_jitter(height = .15) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2))
```
#Density shows proportion, while the box plots show range
### Exercise 3

```{r}
ggplot(plastic_waste) +
  aes(x = continent,
      y = plastic_waste_per_cap,
      fill = continent,
      color = continent) +
  geom_point()
```
```{r}
ggplot(plastic_waste) +
  aes(x = plastic_waste_per_cap,
      y = total_pop,) +
  geom_point()
```
```{r plastic-waste-population-total}
ggplot(plastic_waste) +
  aes(x = total_pop,
      y = plastic_waste_per_cap,
      fill = plastic_waste_per_cap,
      color = plastic_waste_per_cap) +
  geom_point() +
  geom_smooth(color = "black",
              fill = "black")
```
```{r plastic-waste-population-coastal}
ggplot(plastic_waste) +
  aes(x = coastal_pop,
      y = plastic_waste_per_cap,
      fill = plastic_waste_per_cap,
      color = plastic_waste_per_cap) +
  geom_point() +
  geom_smooth(color = "black",
              fill = "black")
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r plastic-waste-violin}
# insert code here
```


### Excercise 3

Try this :D

```{r}
ggplot(data = plastic_waste, 
       mapping = aes(x = continent, 
                     y = plastic_waste_per_cap)) +
  geom_violin()+
  geom_boxplot(width=.3, fill="green") +
  stat_summary(fun.y=median, geom="point") 
```

### Exercise 5 

Helpful reference:http://www.sthda.com/english/wiki/ggplot2-themes-and-background-colors-the-3-elements


