---
title: "Lab 6"
author: "Angelina Venetto"
date: "3/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("singer")
```
```{r}
songs <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/songs.csv")
locations <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/loc.csv")

(time <- as_tibble(songs) |> 
   rename(song = title))

(album <- as_tibble(locations) |> 
   select(title, everything()) |> 
   rename(album = release,
          song  = title))
```
#1. join songs and corresponding albums. We know the corresponding albums for Grievance, Stupidmop, President Tense, MFc, Lukin, It's Lulu, Sparrow, etc. 
```{r}
time |> 
  left_join(album, by = "song")
```
#2. Add corresponding albums to "time" tibble, whuile perserving rows even if album info is not available 
```{r}
time |> 
  full_join(album, by = "song")
```
#2. Songs in year but no album info 
```{r}
time |> 
  full_join(album, by = "song")
```

#3. Year with no album info
```{r}
time |> 
  left_join(album, by = "song")
```

#4 Artists in time but not album

```{r}
time |> 
  anti_join(album, by = "artist_name")
```

#join all tibbles

```{r}
time |> 
  full_join(album, by = "song")
```
```{r}
fell <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Fellowship_Of_The_Ring.csv")
ttow <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Two_Towers.csv")
retk <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Return_Of_The_King.csv")
```

#1

```{r}
full_join(fell, ttow)
```

#2

```{r}
fell |> 
  anti_join(retk, by = "Race") |> 
   anti_join(ttow, by = "Race")
```

#Exercise 3

```{r}
(y <-  tibble(x1 = LETTERS[1:3], x2 = 1:3))
(z <- tibble(x1 = c("B", "C", "D"), x2 = 2:4))
```

#1

```{r}
full_join(y, z)
```

#2

```{r}
full_join(
  mutate(y, day = "Day 1"),
  mutate(z, day = "Day 2")
)
```

#3

```{r}
anti_join(z, y)
```
