---
title: "Lab-402152022"
author: "Angelina Venetto"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(dplyr)
```

```{r}
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
```
```{r}
green_data |> 
  pull(open10) |> 
  unique()
```
```{r}
green_data |> 
  select(-id) |> 
  unlist() |> 
  unique()
```
```{r}
green_data <- green_data |> 
  mutate(
    across(
     -id,
     \(x) recode(x,"1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5
                 "-99" = NA_real_  )
    )
  )
```
```{r}
green_data <- green_data |> 
mutate(
    across(
     -id,
     \(x) na_if(x, -99)
    )
  )
```
```{r}
green_data <- green_data |> 
mutate(
  green2 = recode(green2, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1) comp6 = max(comp6, na.IM = TRUE) - min(comp6, na.rm = TRUE) - comp6
  )
```

```{r}
green_data <- green_data |> 
mutate(
  across(
    c(green2, comp6, comp7)
               )
  )
  
```